// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg8PSXnYE6_MJafvJN-OTw_biUJ29tuTw',
    appId: '1:216478379013:web:95c75c433a00df3f8e806c',
    messagingSenderId: '216478379013',
    projectId: 'archeology-30306',
    authDomain: 'archeology-30306.firebaseapp.com',
    databaseURL: 'https://archeology-30306-default-rtdb.firebaseio.com',
    storageBucket: 'archeology-30306.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjW4ypJQ2-svjfljNYEWRjRX8osU5Gm84',
    appId: '1:216478379013:android:a69b88da8a398d8e8e806c',
    messagingSenderId: '216478379013',
    projectId: 'archeology-30306',
    databaseURL: 'https://archeology-30306-default-rtdb.firebaseio.com',
    storageBucket: 'archeology-30306.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSY8B9aKXgx8-S0og3UDWTw-G5OMtlkVk',
    appId: '1:216478379013:ios:327d014388c2a30a8e806c',
    messagingSenderId: '216478379013',
    projectId: 'archeology-30306',
    databaseURL: 'https://archeology-30306-default-rtdb.firebaseio.com',
    storageBucket: 'archeology-30306.appspot.com',
    iosClientId: '216478379013-ed8o0uve5ldudtgsee8th1gpv13940gk.apps.googleusercontent.com',
    iosBundleId: 'com.example.archeology',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSY8B9aKXgx8-S0og3UDWTw-G5OMtlkVk',
    appId: '1:216478379013:ios:e585079587d3b06d8e806c',
    messagingSenderId: '216478379013',
    projectId: 'archeology-30306',
    databaseURL: 'https://archeology-30306-default-rtdb.firebaseio.com',
    storageBucket: 'archeology-30306.appspot.com',
    iosClientId: '216478379013-r45grbqocil9l5kkrp3d3g95ukjsfv0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.archeology.RunnerTests',
  );
}
